### ISSUE TITLE
[PACKAGE REQUEST] Optimus Manager QT

### ISSUE THREAD

**Issue by bluebeargreen-2** [devOS-Sanity-Edition/devos-arch-reporting#3]
**Is it from the Official Arch Repositories or the AUR?**
AUR

**Package Name show in the repository**
optimus-manager-qt

**Description/What does it do?**
Used for optimus NVIDIA laptops for switching between dGPU, Hybrid, or iGPU

**When was it last updated?**
August 18, 2021

**Do you agree that this is merely a *suggested* package, and there's no guarantees of it making it into either the Calamares `netinstall` or the distro?:** Yes

**Comment by HiItsDevin** [comment]
Adding to `netinstall` soon, probably won't bundle as it could be conflicting for desktop users.

**Comment by HiItsDevin** [comment]
Added in to `netinstall`
